version: '3'

networks:
  srv:
     external: true

services:
  wp:
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html # Full wordpress project
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
    labels:
      - "traefik.backend=wordpress_${SUBDOMAIN}"
      - "traefik.docker.network=${TNETWORK}"
      - "traefik.frontend.rule=Host:${SUBDOMAIN}.${DOMAIN}"
      - "traefik.enable=true"
      - "traefik.port=80"
    networks:
      - millerdev_srv



  wpcli:
    image: wordpress:cli
    volumes:
      - ./config/php.conf.ini:/usr/local/etc/php/conf.d/conf.ini
      - ./wp-app:/var/www/html
    depends_on:
      - wp
    networks:
      - srv

